- src/gatling/simulations/scenarios/Login.scala
no jira
- homepage content was changed hence required update in performance test.
```
[ ] Yes
[X] No
```
> homepage text change

- src/gatling/simulations/scenarios/NFD_DivorceApplication.scala
> Fix csrf issue.

- Jenkinsfile_nightly
- src/gatling/simulations/simulations/NFD_Pipeline.scala
- src/gatling/simulations/utils/Environment.scala
https://tools.hmcts.net/jira/browse/NFDIV-729
Creating a simulation for performance test and Jenkins pipeline
```
[ ] Yes
[X] No
```
> Simulation to allow perftest or pipeline

- src/gatling/simulations/scenarios/NFD_02DivorceApplication.scala
Update field names
```
[ ] Yes
[x] No
```
> Update field names

- src/gatling/simulations/scenarios/NFD_02DivorceApplication.scala
Update the legal proceedings field names
```
[ ] Yes
[x] No
```
> Update the legal proceedings field names

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
https://tools.hmcts.net/jira/browse/NFDIV-1086
```
[ ] Yes
[X] No
```
> update path for NFDIV-1086

- src/gatling/simulations/scenarios/CCDAPI.scala
- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
- src/gatling/simulations/scenarios/NFD_03_CitizenApplyForCO.scala
N/A
Shortening long transaction names
```
[ ] Yes
[X] No
```
> Shortening long transaction names

- src/gatling/simulations/scenarios/Homepage.scala
N/A
Updating homepage transaction name
```
[ ] Yes
[X] No
```
> Updating homepage transaction name

- src/gatling/resources/application.conf
N/A
Updating client-secret vault
```
[ ] Yes
[X] No
```
> Updating client-secret vault

- Jenkinsfile_nightly
- src/gatling/resources/application.conf
N/A
Updating client secret details
```
[ ] Yes
[X] No
```
> Updating client secret details

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
N/A
Adding new solicitor-represented screen
```
[ ] Yes
[X] No
```
> Adding new solicitor-represented screen

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
N/A
Updating scripts based on code changes
```
[ ] Yes
[X] No
```
> Updating scripts based on code changes

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
N/A
Updating connections based on code change
```
[ ] Yes
[X] No
```
> Updating connections based on code change

- src/gatling/simulations/scenarios/NFD_03_CitizenApplyForCO.scala
N/A
Updating CO text
```
[ ] Yes
[X] No
```
> Updating CO text

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
N/A
Updating flow with removed page
```
[ ] Yes
[X] No
```
> Updating flow with removed page

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
Update the frontend statement of truth field name as per https://github.com/hmcts/nfdiv-frontend/pull/2129/files
```
[ ] Yes
[x] No
```
> Update statement of truth field name

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
- https://tools.hmcts.net/jira/browse/NFDIV-2197
- reinstate welsh-or-english page
```
[ ] Yes
[X] No
```
> nfdiv-2197: reinstate welsh-or-english page

- src/gatling/resources/bodies/events/UpdateCaseWithCourtHearing.json
Update coDateAndTimeOfHearing format to fix tests
```
[ ] Yes
[x] No
```
> Update coDateAndTimeOfHearing format

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
Request name update for Enter your names
```
[ ] Yes
[x] No
```
> Request name update for Enter your names

- src/gatling/resources/bodies/events/GrantFinalOrder.json
- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
- src/gatling/simulations/scenarios/NFD_03_CitizenApplyForCO.scala
- src/gatling/simulations/scenarios/NFD_04_CitizenApplyForFO.scala
- src/gatling/simulations/simulations/NFD_Simulation.scala
- src/gatling/simulations/utils/CsrfCheck.scala
N/A
Adding Final Order + updating random string generation
```
[ ] Yes
[X] No
```
> Adding FO + Minor Changes

- src/gatling/simulations/scenarios/Login.scala
- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
N/A
Fixing applicant names for joint applications
```
[ ] Yes
[X] No
```
> Fixing applicant names bug for joint apps

- src/gatling/simulations/utils/Environment.scala
GOV UK changed their payments domain URL. Updating the performance tests to reflect this change.
```
[ ] Yes
[X] No
```
> Update gov UK pay URL from www.payments to card.payments

- build.gradle
- gradlew
N/A
Upgrading to Java 17
```
[ ] Yes
[X] No
```
> Upgrading to Java 17

- build.gradle
N/A
Upgrading Gatling to 3.9.3 and upgrading dependencies to latest compatible versions.
```
[ ] Yes
[X] No
```
> Updating Gating version and dependencies

- src/gatling/resources/bodies/events/SetCODetails.json
- src/gatling/resources/bodies/events/SetCOEligibilityDates.json
- src/gatling/resources/bodies/events/UpdateCaseWithCourtHearing.json
- src/gatling/simulations/simulations/NFD_Simulation.scala
N/A
Updating CO dates and dueDate
```
[ ] Yes
[X] No
```
> Updating CO dates and dueDate

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/gatling/conf/gatling.conf
- src/gatling/resources/bodies/events/SetCODetails.json
- src/gatling/resources/bodies/events/SetCOEligibilityDates.json
- src/gatling/resources/bodies/events/SetFOEligibilityDates.json
- src/gatling/resources/bodies/events/UpdateCaseWithCourtHearing.json
- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
- src/gatling/simulations/scenarios/NFD_04_CitizenApplyForFO.scala
- src/gatling/simulations/utils/Common.scala
N/A
Dynamic dates and eligibility fix
```
[ ] Yes
[X] No
```
> Dynamic dates and eligibility fix

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/gatling/conf/gatling.conf
- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
N/A
Upgrading to Gatling 3.9.5
```
[ ] Yes
[X] No
```
> Upgrading to Gatling 3.9.5

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/gatling/conf/gatling.conf
N/A
Upgrade Gatling to 3.9.5
```
[ ] Yes
[X]  No
```
> Upgrade Gatling to 3.9.5

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
N/A
Adding in new pages to the citizen flows for confirming names
> Adding new ConfirmName pages

- src/gatling/simulations/simulations/NFD_Simulation.scala
N/A
Updating DenyList to block requests to webchat
> Updating DenyList to block requests to webchat

- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
> Fix issue with performance test

- .github/workflows/stale.yml
https://tools.hmcts.net/jira/browse/NFDIV-4430
New workflow to mark PRs as stale or closed automatically.
Not required
> NFDIV-4430 - New workflow to mark PRs as stale or closed automatically.

- .github/workflows/stale.yml
https://tools.hmcts.net/jira/browse/NFDIV-4430
Workflow scheduled to run at 3AM everyday
> Nfdiv-4430 Workflow scheduled to run at 3AM everyday

- src/gatling/simulations/scenarios/NFD_01_CitizenApplication.scala
https://tools.hmcts.net/jira/browse/NFDIV-4530
> [NFDIV-4530] Update text used for assertion

- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
- src/gatling/simulations/simulations/NFD_Simulation.scala
https://tools.hmcts.net/jira/browse/NFDIV-4538
> [NFDIV-4538] Update test assertions for pre-RFI

- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
- src/gatling/simulations/simulations/NFD_Simulation.scala
> Remove specific assertions that dont relate to performance

- README.adoc
- src/gatling/simulations/scenarios/NFD_03_CitizenApplyForCO.scala
- src/gatling/simulations/simulations/NFD_Simulation.scala
- Removing additional status check, as this varies for each flow. The count can be 1, 2 or 3 for different flows, so it's unnecessary.
- Updating pause time in debug mode to 2s to remove intermittent issues with debug runs
- Updating readme
> Fixes and improved debugging reliability

- build.gradle
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> Remove deprecated property for pipeline fix

- src/gatling/simulations/scenarios/NFD_02_CitizenRespondent.scala
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> Update tests to account for new frontend text
